services:

  app:
    build: .
    command: poetry run python main.py
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_DB_USER}:${POSTGRES_DB_PASSWORD}@db:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
 
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: